### ISSUE TITLE
tip: bind to CTRL+ and CTRL-

### ISSUE THREAD

**Issue by jabbalaci** [cofi/evil-numbers#5]
Hi,

This is not a bug report, just a comment. Thanks a lot for this package. I use the following binding:

```
(define-key evil-normal-state-map (kbd "C-<kp-add>") 'evil-numbers/inc-at-pt)
(define-key evil-normal-state-map (kbd "C-<kp-subtract>") 'evil-numbers/dec-at-pt)
```

kp-add and kp-subtract are the "+" and "-" keys on the keypad on the right side. I find it more intuitive. First I added to C-a and C-x but then I realized that Emacs uses C-x a lot.

Best,

Laszlo

**Comment by cofi** [comment]
Hi Laszlo,

thank you. I'll add it to the README.

Personally, I use plain `+` and `-` but as they are already bound by evil (and vim) I didn't feel comfortable with such an recommendation.
However, the keypad variants are a good alternative (as long as one stays away from laptops or terminal emacs ;))
